### PR TITLE
Implement initial higher-level APIs

### LINKED ISSUE #2: Add feature like pywikibot
I'd like to implement features like [`pywikibot`](https://github.com/wikimedia/pywikibot) or [`MediaWikiAPI`](https://github.com/lehinevych/MediaWikiAPI). Users don't need to know the detail of [`MediaWiki API`](https://www.mediawiki.org/wiki/API:Main_page), they just need to know what function they need to call. Like the below pseudo code:

```typescript
import {bot} from 'https://deno.land/x/mediawiki/api/mod.ts';

// omit some code

const page = bot.Page("Microsoft");
console.log(page.text); // Print the content of "Microsoft" page.

const category = bot.Category("music");
console.log(page.articles); // Print the list of page names whose category is "Music"
```

If you have any suggestion, please let me know. Thanks!

### PR DESCRIPTION
**Pull request by benebsiny**
Continues #3 

Create a `bot` object so that a user can read / update / delete a page more easily. (close #2)

### Page
A user can read a page by the following code:
```typescript
const site = Bot.site(SiteUrl.wikipedia("en"));  // English wikipedia site
// const site = Bot.site("https://en.wikipedia.org/w/api.php");  // This is also available
const page = await site.page("Software_testing");
console.log(page.text);  // Print the content of "Test_Page" page
```
If a user want to edit / delete a page, they can login via [bot password](https://www.mediawiki.org/wiki/Manual:Bot_passwords) to edit / delete a page. (Login via user's name and password hasn't implemented yet)
```typescript
const site = Bot.site("https://test.wikipedia.org");
await site.login("Bot_username", "Bot_password");
const page = await site.page("Test_Page");

// Edit
page.text = "Hello World";  // Change content of page into "Hello World"
await page.save("Update it!!");  // Save

// Delete
await page.delete();
```

### Category
A user can get the pages that belong to the specific category.
```typescript
const site = Bot.site("https://test.wikipedia.org");
const cat = await site.category("Cat");
console.log(cat.articles); // ["American Shorthair", "Burmese cats", "Cymric cat", ...]
```

## Done
- [X] User can read a page
- [X] Support bot login
- [X] Bot can edit / delete a page with login status

## TODO (Some trivial ones might not listed)
- [x] Fix "undefined" string problem. When a user doesn't pass argument to the function, the relevant argument would become "undefined" string.
- [X] Support `category` lookup.
- [ ] ~~Support login via user's name and password.~~ (It seems that `clientlogin` API should work with authentication. The example in [official API page](https://www.mediawiki.org/wiki/API:Login#Method_2._clientlogin) is different from its documentation.)
- [X] Predefined the API URL of the wikis, so that users don't need to find what's the API URL
- [X] Error handling. When an HTTP request isn't successful, shows the messages to users.
- [X] Add testing
- [x] Add instruction (or document) of `bot` into README.md.

### CODE REVIEW

**Comment by rojvv** [comment]
Thanks for opening the PR again, sorry for the inconvenience. I will make some minor modifications, and talk to you about larger modifications. Once everything is done, we’ll release it.

**Review by rojvv — COMMENTED** [review]
I am concerned with the name `bot`. And don’t you think `Site` and `Bot` should be merged into a single class?

**Comment by benebsiny** [comment]
> I am concerned with the name `bot`.

How come? Is the name too common?

> And don’t you think Site and Bot should be merged into a single class?

Yes, we could merge them together. The reason why pywikibot initial a Site instance by calling a static function is to cache the Site object. But I think it's not necessary in this repo.

**Comment by rojvv** [comment]
> How come? Is the name too common?

The name `bot` to me feels like something that automates things, but no problem, I think we’ll be adding more methods that will complete the name in the future.

> Yes, we could merge them together. The reason why pywikibot initial a Site instance by calling a static function is to cache the Site object. But I think it's not necessary in this repo.

Can you merge them then?

**Comment by benebsiny** [comment]
I've merged them. Also update the testing and README.md.

**Review by rojvv — COMMENTED** [review]
Oh, no. I meant this:

```ts
const bot = new Bot(SiteUrl.wikipedia("test"));
```

**Comment by benebsiny** [comment]
Oops, sorry I misunderstood your meaning... I'll try again

**Comment by rojvv** [comment]
No problem at all. It’s only me and you in the universe working on this.

**Comment by benebsiny** [comment]
I've rename it...! Also the variable names are changed from `site` to `bot`.

**Review by rojvv — APPROVED** [review]
LGTM. Thank you so much!

There’s some improvements that can be made, but we’ll do them in follow-ups. For example, making the `Page` class not take `Bot` to not have circular dependencies.

**Pull request merged**
