### PR TITLE
Add pywikibot-like bots

### LINKED ISSUE #2: Add feature like pywikibot
I'd like to implement features like [`pywikibot`](https://github.com/wikimedia/pywikibot) or [`MediaWikiAPI`](https://github.com/lehinevych/MediaWikiAPI). Users don't need to know the detail of [`MediaWiki API`](https://www.mediawiki.org/wiki/API:Main_page), they just need to know what function they need to call. Like the below pseudo code:

```typescript
import {bot} from 'https://deno.land/x/mediawiki/api/mod.ts';

// omit some code

const page = bot.Page("Microsoft");
console.log(page.text); // Print the content of "Microsoft" page.

const category = bot.Category("music");
console.log(page.articles); // Print the list of page names whose category is "Music"
```

If you have any suggestion, please let me know. Thanks!

### PR DESCRIPTION
**Pull request by benebsiny**
Create a `bot` object so that a user can read / update / delete a page more easily. (close #2)

### Page
A user can read a page by the following code:
```typescript
const site = Bot.site(SiteUrl.wikipedia("en"));  // English wikipedia site
// const site = Bot.site("https://en.wikipedia.org/w/api.php");  // This is also available
const page = await site.page("Software_testing");
console.log(page.text);  // Print the content of "Test_Page" page
```
If a user want to edit / delete a page, they can login via [bot password](https://www.mediawiki.org/wiki/Manual:Bot_passwords) to edit / delete a page. (Login via user's name and password hasn't implemented yet)
```typescript
const site = Bot.site("https://test.wikipedia.org");
await site.login("Bot_username", "Bot_password");
const page = await site.page("Test_Page");

// Edit
page.text = "Hello World";  // Change content of page into "Hello World"
await page.save("Update it!!");  // Save

// Delete
await page.delete();
```

### Category
A user can get the pages that belong to the specific category.
```typescript
const site = Bot.site("https://test.wikipedia.org");
const cat = await site.category("Cat");
console.log(cat.articles); // ["American Shorthair", "Burmese cats", "Cymric cat", ...]
```

## Done
- [X] User can read a page
- [X] Support bot login
- [X] Bot can edit / delete a page with login status

## TODO (Some trivial ones might not listed)
- [x] Fix "undefined" string problem. When a user doesn't pass argument to the function, the relevant argument would become "undefined" string.
- [X] Support `category` lookup.
- [ ] ~~Support login via user's name and password.~~ (It seems that `clientlogin` API should work with authentication. The example in [official API page](https://www.mediawiki.org/wiki/API:Login#Method_2._clientlogin) is different from its documentation.)
- [X] Predefined the API URL of the wikis, so that users don't need to find what's the API URL
- [X] Error handling. When an HTTP request isn't successful, shows the messages to users.
- [X] Add testing
- [x] Add instruction (or document) of `bot` into README.md.

### CODE REVIEW

**Comment by rojvv** [comment]
First of all, thank you for caring and contributing to this!

What do you think if we move this to its own directory, say `/bot`? `/api` is intended for raw functions and stuff like that.

**Comment by benebsiny** [comment]
> What do you think if we move this to its own directory, say /bot?

@roj1512 That's a great idea. I've moved it. Have a look at it 😄

**Comment by rojvv** [comment]
Much better now.

**Comment by benebsiny** [comment]
@roj1512 Hi. Because the fandom's language code is in the pathname instead of in the hostname, it's a little bit complex to handle it with the current `apiUrl` function in `client.ts`, so I'd like to change it to make it accept the Wiki's API URL instead of Wiki's URL. For example:
```typescript
// use this
const client = new Client("https://en.wikipedia.org/w/api.php");

// instead of this
const client = new Client("https://en.wikipedia.org");
```

Would you agree this proposal?

P.S.
If `Client` accept the Wiki's API URL, users can also call the `WikiFamily.Wikipedia()` to get Wikipedia's API URL. This is under development.
```typescript
const client = new Client(WikiFamily.Wikipedia('zh')); // `WikiFamily.Wikipedia('zh')` returns "https://zh.wikipedia.org/w/api.php".
const client = new Client(WikiFamily.Fandom("youtube", 'en'));  // `WikiFamily.Fandom("youtube", 'en')` returns "https://youtube.fandom.com/en/api.php"
```

**Comment by rojvv** [comment]
This is nice. What do you think if it was a class named `Site` with static methods starting with lowercase characters, like `Site.wikipedia()`, `Site.fandom()`, etc?

**Comment by benebsiny** [comment]
> What do you think if it was a class named `Site` with static methods starting with lowercase characters

Unfortunately there's already a class named `Site`, How about using `WikiSite`? e.g. `WikiSite.wikipedia()`.

**Comment by rojvv** [comment]
How about a utility function like this?

```ts
const siteGetters = {
    wikipedia: (...) => ...,
    fandom: (...) => ...
}
function getSite(site: keyof typeof siteGetters, ...args) {
  return siteGetters(site)(..args);
}
 ```

**Comment by benebsiny** [comment]
> How about a utility function like this?

Number of arguments of each site are different. This looks not clearly to know what argument should pass.

I'd rather separate them to different functions, currently implementation like this:
```typescript
type FamilyCode = "ar" | "cs" | ...;

export class WikiSite {
    static fandom(communityName: string, code: FamilyCode = 'en') {
        if (communityName.match(/^[a-zA-Z0-9\-]{0,50}$/)) {
            return `https://${communityName}.fandom.com/${code}/api.php`;
        } else {
            throw new Error("Invalid Fandom site name");
        }
    }

    static mediawiki() {
        return "https://www.mediawiki.org/w/api.php";
    }

    static wikipedia(code: FamilyCode = 'en') {
        return `https://${code}.wikipedia.org/w/api.php`
    }
}
```

**Comment by rojvv** [comment]
Good. The class name could be `SiteUrl`.

**Comment by benebsiny** [comment]
@roj1512 Hi, I've finish basic function for the bot, please reviews my pull requests, thanks!

**Comment by rojvv** [comment]
@benebsiny I think I ruined this PR, and we cannot reopen it. Can you open another one from the same branch? Your work is not lost, only the history was changed.

**Comment by benebsiny** [comment]
@roj1512 How about pulling my `main` branch and then force-push to your `main` branch? It seems that all your commit IDs are all different from the original commit IDs and they all became `unverified`.

image

**Comment by rojvv** [comment]
Hmm, I’ll see if I can sign them.

**Comment by rojvv** [comment]
@benebsiny I signed the commits again. Rebase ISSUE-2 and open a new PR.

**Pull request closed without merging**
